default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: whaler
  username: root
  password: root
  host: localhost
  port: 3306
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock